//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNK.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhMucToDanPho
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DanhMucToDanPho()
        {
            this.HoKhaus = new HashSet<HoKhau>();
        }
    
        public int Id { get; set; }
        public string TenVietTat { get; set; }
        public string TenDayDu { get; set; }
        public int MaKhuVuc { get; set; }
        public int MaKhuPho { get; set; }
        public bool TrangThai { get; set; }
    
        public virtual DanhMucKhuPho DanhMucKhuPho { get; set; }
        public virtual DanhMucKhuVuc DanhMucKhuVuc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoKhau> HoKhaus { get; set; }
    }
}
