//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace QLNK.EF
{
    public partial class DanhMucDuong
    {
        public int Id { get; set; }

        [DisplayName("Số thứ tự")]
        public int SoThuTu { get; set; }

        [DisplayName("Tên viết tắt")]
        public string TenVietTat { get; set; }
        [DisplayName("Tên đường")]
        public string TenDayDu { get; set; }
        [DisplayName("Trạng thái")]
        public bool TrangThai { get; set; }
    }
}
