//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNK.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoKhau
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoKhau()
        {
            this.NhanKhaus = new HashSet<NhanKhau>();
        }
    
        public int Id { get; set; }
        public string TenVietTat { get; set; }
        public string TenDayDu { get; set; }
        public string DiaChi { get; set; }
        public int MaToDanPho { get; set; }
        public int MaKhuVuc { get; set; }
        public int MaTinhTrangNhaO { get; set; }
        public int MaLoaiHoSo { get; set; }
        public System.DateTime NgayDangKy { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public bool TrangThai { get; set; }
    
        public virtual DanhMucKhuVuc DanhMucKhuVuc { get; set; }
        public virtual DanhMucToDanPho DanhMucToDanPho { get; set; }
        public virtual LoaiHoSo LoaiHoSo { get; set; }
        public virtual TinhTrangNhaO TinhTrangNhaO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhanKhau> NhanKhaus { get; set; }
    }
}
