//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace QLNK.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiDung
    {
        public int Id { get; set; }
        [DisplayName("Họ và tên")]
        public string TenNguoiDung { get; set; }
        [DisplayName("Tên đăng nhập")]
        public string TenDangNhap { get; set; }
        [DisplayName("Mật khẩu")]
        public string MatKhau { get; set; }
        [DisplayName("Chức vụ")]
        public string ChucVu { get; set; }
        [DisplayName("Quyền hạn")]
        public string QuyenHan { get; set; }
        [DisplayName("Trạng thái")]
        public bool TrangThai { get; set; }
    }
}
