//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNK.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLNhanKhau_DBEntities : DbContext
    {
        public QLNhanKhau_DBEntities()
            : base("name=QLNhanKhau_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CauHinhChung> CauHinhChungs { get; set; }
        public virtual DbSet<DanhMucDuong> DanhMucDuongs { get; set; }
        public virtual DbSet<DanhMucKhuPho> DanhMucKhuPhoes { get; set; }
        public virtual DbSet<DanhMucKhuVuc> DanhMucKhuVucs { get; set; }
        public virtual DbSet<DanhMucToDanPho> DanhMucToDanPhoes { get; set; }
        public virtual DbSet<HoKhau> HoKhaus { get; set; }
        public virtual DbSet<LoaiHoSo> LoaiHoSoes { get; set; }
        public virtual DbSet<NguoiDung> NguoiDungs { get; set; }
        public virtual DbSet<NhanKhau> NhanKhaus { get; set; }
        public virtual DbSet<TinhTrangCuTru> TinhTrangCuTrus { get; set; }
        public virtual DbSet<TinhTrangNhaO> TinhTrangNhaOs { get; set; }
    }
}
