//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace QLNK.EF
{
    using System.Collections.Generic;

    public partial class TinhTrangNhaO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TinhTrangNhaO()
        {
            this.HoKhaus = new HashSet<HoKhau>();
        }

        public int Id { get; set; }
        [DisplayName("Số thứ tự")]
        public int SoThuTu { get; set; }
        [DisplayName("Tình trạng nhà ở")]
        public string ChiTietTinhTrangNhaO { get; set; }
        [DisplayName("Trạng thái")]
        public bool TrangThai { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoKhau> HoKhaus { get; set; }
    }
}
