//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace QLNK.EF
{
    public partial class TinhTrangCuTru
    {
        public int Id { get; set; }
        [DisplayName("Số thứ tự")]
        public int STT { get; set; }

        [DisplayName("Tên tình trạng")]
        public string ChiTietTinhTrangCuTru { get; set; }
        public bool TrangThai { get; set; }
    }
}
